# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Arpegio' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Arpegio
  pod 'Texture'
  pod 'FirebaseCore'
  pod 'FirebaseAuth'
  pod 'FirebaseDatabase'
  pod 'FirebaseStorage'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'JGProgressHUD'

end
